name: question_master
description: Answer questions as fast as you can

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  confetti: ^0.7.0
  easy_localization: ^3.0.1
  get_it: ^7.2.0
  rxdart: ^0.27.5
  riverpod: ^1.0.3
  hooks_riverpod: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/icon/logo.png"
    background_color: "#fee459"
    theme_color: "#fee459"
  image_path: "assets/images/icon/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/icon/logo.png"
  adaptive_icon_background: "#fee459"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
